namespace InventoryManagementSystem
{
    partial class Product
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Product));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.ProductsGridView = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuShadowPanel4 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.bunifuShadowPanel6 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.AddButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.RemoveButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.UpdateButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.QualityBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.TypeBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.PriceBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.QuantityBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.NameBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuShadowPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ProductsGridView)).BeginInit();
            this.bunifuShadowPanel6.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.White;
            this.bunifuShadowPanel1.BorderRadius = 10;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.Controls.Add(this.ProductsGridView);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuShadowPanel4);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(5, 211);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.White;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.White;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 5;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(796, 387);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 3;
            this.bunifuShadowPanel1.ControlAdded += new System.Windows.Forms.ControlEventHandler(this.bunifuShadowPanel1_ControlAdded);
            // 
            // ProductsGridView
            // 
            this.ProductsGridView.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.ProductsGridView.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.ProductsGridView.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.ProductsGridView.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.ProductsGridView.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.ProductsGridView.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.ProductsGridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.ProductsGridView.ColumnHeadersHeight = 40;
            this.ProductsGridView.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.ProductsGridView.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.ProductsGridView.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.ProductsGridView.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(194)))), ((int)(((byte)(194)))));
            this.ProductsGridView.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.ProductsGridView.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.ProductsGridView.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(194)))), ((int)(((byte)(194)))));
            this.ProductsGridView.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.ProductsGridView.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.ProductsGridView.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.ProductsGridView.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.ProductsGridView.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.ProductsGridView.CurrentTheme.Name = null;
            this.ProductsGridView.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.ProductsGridView.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.ProductsGridView.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.ProductsGridView.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.ProductsGridView.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.ProductsGridView.DefaultCellStyle = dataGridViewCellStyle3;
            this.ProductsGridView.EnableHeadersVisualStyles = false;
            this.ProductsGridView.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(194)))), ((int)(((byte)(194)))));
            this.ProductsGridView.HeaderBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.ProductsGridView.HeaderBgColor = System.Drawing.Color.Empty;
            this.ProductsGridView.HeaderForeColor = System.Drawing.Color.White;
            this.ProductsGridView.Location = new System.Drawing.Point(14, 16);
            this.ProductsGridView.Name = "ProductsGridView";
            this.ProductsGridView.RowHeadersVisible = false;
            this.ProductsGridView.RowTemplate.Height = 40;
            this.ProductsGridView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.ProductsGridView.Size = new System.Drawing.Size(768, 359);
            this.ProductsGridView.TabIndex = 1;
            this.ProductsGridView.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // bunifuShadowPanel4
            // 
            this.bunifuShadowPanel4.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel4.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel4.BorderRadius = 10;
            this.bunifuShadowPanel4.BorderThickness = 1;
            this.bunifuShadowPanel4.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel4.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel4.Location = new System.Drawing.Point(-438, -151);
            this.bunifuShadowPanel4.Name = "bunifuShadowPanel4";
            this.bunifuShadowPanel4.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel4.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel4.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel4.ShadowDept = 2;
            this.bunifuShadowPanel4.ShadowDepth = 3;
            this.bunifuShadowPanel4.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel4.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel4.Size = new System.Drawing.Size(206, 270);
            this.bunifuShadowPanel4.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel4.TabIndex = 0;
            // 
            // bunifuShadowPanel6
            // 
            this.bunifuShadowPanel6.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel6.BorderColor = System.Drawing.Color.Gray;
            this.bunifuShadowPanel6.BorderRadius = 10;
            this.bunifuShadowPanel6.BorderThickness = 1;
            this.bunifuShadowPanel6.Controls.Add(this.AddButton);
            this.bunifuShadowPanel6.Controls.Add(this.RemoveButton);
            this.bunifuShadowPanel6.Controls.Add(this.UpdateButton);
            this.bunifuShadowPanel6.Controls.Add(this.QualityBox);
            this.bunifuShadowPanel6.Controls.Add(this.bunifuLabel3);
            this.bunifuShadowPanel6.Controls.Add(this.TypeBox);
            this.bunifuShadowPanel6.Controls.Add(this.bunifuLabel2);
            this.bunifuShadowPanel6.Controls.Add(this.PriceBox);
            this.bunifuShadowPanel6.Controls.Add(this.bunifuLabel5);
            this.bunifuShadowPanel6.Controls.Add(this.QuantityBox);
            this.bunifuShadowPanel6.Controls.Add(this.bunifuLabel4);
            this.bunifuShadowPanel6.Controls.Add(this.NameBox);
            this.bunifuShadowPanel6.Controls.Add(this.bunifuLabel6);
            this.bunifuShadowPanel6.Controls.Add(this.bunifuLabel1);
            this.bunifuShadowPanel6.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel6.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel6.Location = new System.Drawing.Point(5, 6);
            this.bunifuShadowPanel6.Name = "bunifuShadowPanel6";
            this.bunifuShadowPanel6.PanelColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(239)))), ((int)(((byte)(234)))));
            this.bunifuShadowPanel6.PanelColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(239)))), ((int)(((byte)(234)))));
            this.bunifuShadowPanel6.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel6.ShadowDept = 2;
            this.bunifuShadowPanel6.ShadowDepth = 4;
            this.bunifuShadowPanel6.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel6.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel6.Size = new System.Drawing.Size(796, 207);
            this.bunifuShadowPanel6.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel6.TabIndex = 0;
            this.bunifuShadowPanel6.ControlAdded += new System.Windows.Forms.ControlEventHandler(this.bunifuShadowPanel6_ControlAdded);
            // 
            // AddButton
            // 
            this.AddButton.AllowAnimations = true;
            this.AddButton.AllowMouseEffects = true;
            this.AddButton.AllowToggling = false;
            this.AddButton.AnimationSpeed = 200;
            this.AddButton.AutoGenerateColors = false;
            this.AddButton.AutoRoundBorders = false;
            this.AddButton.AutoSizeLeftIcon = true;
            this.AddButton.AutoSizeRightIcon = true;
            this.AddButton.BackColor = System.Drawing.Color.Transparent;
            this.AddButton.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.AddButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AddButton.BackgroundImage")));
            this.AddButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddButton.ButtonText = "Add";
            this.AddButton.ButtonTextMarginLeft = 0;
            this.AddButton.ColorContrastOnClick = 45;
            this.AddButton.ColorContrastOnHover = 45;
            this.AddButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.AddButton.CustomizableEdges = borderEdges1;
            this.AddButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AddButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AddButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AddButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AddButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AddButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AddButton.ForeColor = System.Drawing.Color.White;
            this.AddButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AddButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AddButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AddButton.IconMarginLeft = 11;
            this.AddButton.IconPadding = 10;
            this.AddButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AddButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AddButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AddButton.IconSize = 25;
            this.AddButton.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.AddButton.IdleBorderRadius = 15;
            this.AddButton.IdleBorderThickness = 1;
            this.AddButton.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.AddButton.IdleIconLeftImage = null;
            this.AddButton.IdleIconRightImage = null;
            this.AddButton.IndicateFocus = false;
            this.AddButton.Location = new System.Drawing.Point(638, 54);
            this.AddButton.Name = "AddButton";
            this.AddButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AddButton.OnDisabledState.BorderRadius = 15;
            this.AddButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddButton.OnDisabledState.BorderThickness = 1;
            this.AddButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AddButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AddButton.OnDisabledState.IconLeftImage = null;
            this.AddButton.OnDisabledState.IconRightImage = null;
            this.AddButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AddButton.onHoverState.BorderRadius = 15;
            this.AddButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddButton.onHoverState.BorderThickness = 1;
            this.AddButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AddButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.AddButton.onHoverState.IconLeftImage = null;
            this.AddButton.onHoverState.IconRightImage = null;
            this.AddButton.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.AddButton.OnIdleState.BorderRadius = 15;
            this.AddButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddButton.OnIdleState.BorderThickness = 1;
            this.AddButton.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.AddButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AddButton.OnIdleState.IconLeftImage = null;
            this.AddButton.OnIdleState.IconRightImage = null;
            this.AddButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.AddButton.OnPressedState.BorderRadius = 15;
            this.AddButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AddButton.OnPressedState.BorderThickness = 1;
            this.AddButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.AddButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AddButton.OnPressedState.IconLeftImage = null;
            this.AddButton.OnPressedState.IconRightImage = null;
            this.AddButton.Size = new System.Drawing.Size(142, 39);
            this.AddButton.TabIndex = 6;
            this.AddButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AddButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AddButton.TextMarginLeft = 0;
            this.AddButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.AddButton.UseDefaultRadiusAndThickness = true;
            this.AddButton.Click += new System.EventHandler(this.AddButton_Click);
            // 
            // RemoveButton
            // 
            this.RemoveButton.AllowAnimations = true;
            this.RemoveButton.AllowMouseEffects = true;
            this.RemoveButton.AllowToggling = false;
            this.RemoveButton.AnimationSpeed = 200;
            this.RemoveButton.AutoGenerateColors = false;
            this.RemoveButton.AutoRoundBorders = false;
            this.RemoveButton.AutoSizeLeftIcon = true;
            this.RemoveButton.AutoSizeRightIcon = true;
            this.RemoveButton.BackColor = System.Drawing.Color.Transparent;
            this.RemoveButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(11)))), ((int)(((byte)(11)))));
            this.RemoveButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("RemoveButton.BackgroundImage")));
            this.RemoveButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RemoveButton.ButtonText = "Remove";
            this.RemoveButton.ButtonTextMarginLeft = 0;
            this.RemoveButton.ColorContrastOnClick = 45;
            this.RemoveButton.ColorContrastOnHover = 45;
            this.RemoveButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.RemoveButton.CustomizableEdges = borderEdges2;
            this.RemoveButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.RemoveButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RemoveButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RemoveButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.RemoveButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.RemoveButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.RemoveButton.ForeColor = System.Drawing.Color.White;
            this.RemoveButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.RemoveButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.RemoveButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.RemoveButton.IconMarginLeft = 11;
            this.RemoveButton.IconPadding = 10;
            this.RemoveButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.RemoveButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.RemoveButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.RemoveButton.IconSize = 25;
            this.RemoveButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(11)))), ((int)(((byte)(11)))));
            this.RemoveButton.IdleBorderRadius = 15;
            this.RemoveButton.IdleBorderThickness = 1;
            this.RemoveButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(11)))), ((int)(((byte)(11)))));
            this.RemoveButton.IdleIconLeftImage = null;
            this.RemoveButton.IdleIconRightImage = null;
            this.RemoveButton.IndicateFocus = false;
            this.RemoveButton.Location = new System.Drawing.Point(638, 155);
            this.RemoveButton.Name = "RemoveButton";
            this.RemoveButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RemoveButton.OnDisabledState.BorderRadius = 15;
            this.RemoveButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RemoveButton.OnDisabledState.BorderThickness = 1;
            this.RemoveButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RemoveButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.RemoveButton.OnDisabledState.IconLeftImage = null;
            this.RemoveButton.OnDisabledState.IconRightImage = null;
            this.RemoveButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.RemoveButton.onHoverState.BorderRadius = 15;
            this.RemoveButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RemoveButton.onHoverState.BorderThickness = 1;
            this.RemoveButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.RemoveButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.RemoveButton.onHoverState.IconLeftImage = null;
            this.RemoveButton.onHoverState.IconRightImage = null;
            this.RemoveButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(11)))), ((int)(((byte)(11)))));
            this.RemoveButton.OnIdleState.BorderRadius = 15;
            this.RemoveButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RemoveButton.OnIdleState.BorderThickness = 1;
            this.RemoveButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(11)))), ((int)(((byte)(11)))));
            this.RemoveButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.RemoveButton.OnIdleState.IconLeftImage = null;
            this.RemoveButton.OnIdleState.IconRightImage = null;
            this.RemoveButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.RemoveButton.OnPressedState.BorderRadius = 15;
            this.RemoveButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RemoveButton.OnPressedState.BorderThickness = 1;
            this.RemoveButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.RemoveButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.RemoveButton.OnPressedState.IconLeftImage = null;
            this.RemoveButton.OnPressedState.IconRightImage = null;
            this.RemoveButton.Size = new System.Drawing.Size(142, 39);
            this.RemoveButton.TabIndex = 2;
            this.RemoveButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.RemoveButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.RemoveButton.TextMarginLeft = 0;
            this.RemoveButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.RemoveButton.UseDefaultRadiusAndThickness = true;
            // 
            // UpdateButton
            // 
            this.UpdateButton.AllowAnimations = true;
            this.UpdateButton.AllowMouseEffects = true;
            this.UpdateButton.AllowToggling = false;
            this.UpdateButton.AnimationSpeed = 200;
            this.UpdateButton.AutoGenerateColors = false;
            this.UpdateButton.AutoRoundBorders = false;
            this.UpdateButton.AutoSizeLeftIcon = true;
            this.UpdateButton.AutoSizeRightIcon = true;
            this.UpdateButton.BackColor = System.Drawing.Color.Transparent;
            this.UpdateButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(98)))), ((int)(((byte)(0)))));
            this.UpdateButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("UpdateButton.BackgroundImage")));
            this.UpdateButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateButton.ButtonText = "Update";
            this.UpdateButton.ButtonTextMarginLeft = 0;
            this.UpdateButton.ColorContrastOnClick = 45;
            this.UpdateButton.ColorContrastOnHover = 45;
            this.UpdateButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.UpdateButton.CustomizableEdges = borderEdges3;
            this.UpdateButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.UpdateButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.UpdateButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UpdateButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.UpdateButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.UpdateButton.Font = new System.Drawing.Font("Bebas", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.UpdateButton.ForeColor = System.Drawing.Color.White;
            this.UpdateButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.UpdateButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.UpdateButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.UpdateButton.IconMarginLeft = 11;
            this.UpdateButton.IconPadding = 10;
            this.UpdateButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.UpdateButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.UpdateButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.UpdateButton.IconSize = 25;
            this.UpdateButton.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(98)))), ((int)(((byte)(0)))));
            this.UpdateButton.IdleBorderRadius = 15;
            this.UpdateButton.IdleBorderThickness = 1;
            this.UpdateButton.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(98)))), ((int)(((byte)(0)))));
            this.UpdateButton.IdleIconLeftImage = null;
            this.UpdateButton.IdleIconRightImage = null;
            this.UpdateButton.IndicateFocus = false;
            this.UpdateButton.Location = new System.Drawing.Point(638, 105);
            this.UpdateButton.Name = "UpdateButton";
            this.UpdateButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.UpdateButton.OnDisabledState.BorderRadius = 15;
            this.UpdateButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateButton.OnDisabledState.BorderThickness = 1;
            this.UpdateButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UpdateButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.UpdateButton.OnDisabledState.IconLeftImage = null;
            this.UpdateButton.OnDisabledState.IconRightImage = null;
            this.UpdateButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.UpdateButton.onHoverState.BorderRadius = 15;
            this.UpdateButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateButton.onHoverState.BorderThickness = 1;
            this.UpdateButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.UpdateButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.UpdateButton.onHoverState.IconLeftImage = null;
            this.UpdateButton.onHoverState.IconRightImage = null;
            this.UpdateButton.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(98)))), ((int)(((byte)(0)))));
            this.UpdateButton.OnIdleState.BorderRadius = 15;
            this.UpdateButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateButton.OnIdleState.BorderThickness = 1;
            this.UpdateButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(98)))), ((int)(((byte)(0)))));
            this.UpdateButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.UpdateButton.OnIdleState.IconLeftImage = null;
            this.UpdateButton.OnIdleState.IconRightImage = null;
            this.UpdateButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.UpdateButton.OnPressedState.BorderRadius = 15;
            this.UpdateButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.UpdateButton.OnPressedState.BorderThickness = 1;
            this.UpdateButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.UpdateButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.UpdateButton.OnPressedState.IconLeftImage = null;
            this.UpdateButton.OnPressedState.IconRightImage = null;
            this.UpdateButton.Size = new System.Drawing.Size(142, 39);
            this.UpdateButton.TabIndex = 2;
            this.UpdateButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.UpdateButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.UpdateButton.TextMarginLeft = 0;
            this.UpdateButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.UpdateButton.UseDefaultRadiusAndThickness = true;
            // 
            // QualityBox
            // 
            this.QualityBox.AcceptsReturn = false;
            this.QualityBox.AcceptsTab = false;
            this.QualityBox.AnimationSpeed = 200;
            this.QualityBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.QualityBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.QualityBox.BackColor = System.Drawing.Color.Transparent;
            this.QualityBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("QualityBox.BackgroundImage")));
            this.QualityBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.QualityBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.QualityBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.QualityBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.QualityBox.BorderRadius = 15;
            this.QualityBox.BorderThickness = 1;
            this.QualityBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.QualityBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.QualityBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.QualityBox.DefaultText = "";
            this.QualityBox.FillColor = System.Drawing.Color.White;
            this.QualityBox.HideSelection = true;
            this.QualityBox.IconLeft = null;
            this.QualityBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.QualityBox.IconPadding = 10;
            this.QualityBox.IconRight = null;
            this.QualityBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.QualityBox.Lines = new string[0];
            this.QualityBox.Location = new System.Drawing.Point(418, 107);
            this.QualityBox.MaxLength = 32767;
            this.QualityBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.QualityBox.Modified = false;
            this.QualityBox.Multiline = false;
            this.QualityBox.Name = "QualityBox";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.QualityBox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.QualityBox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.QualityBox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.QualityBox.OnIdleState = stateProperties4;
            this.QualityBox.Padding = new System.Windows.Forms.Padding(3);
            this.QualityBox.PasswordChar = '\0';
            this.QualityBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.QualityBox.PlaceholderText = "Enter text";
            this.QualityBox.ReadOnly = false;
            this.QualityBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.QualityBox.SelectedText = "";
            this.QualityBox.SelectionLength = 0;
            this.QualityBox.SelectionStart = 0;
            this.QualityBox.ShortcutsEnabled = true;
            this.QualityBox.Size = new System.Drawing.Size(152, 37);
            this.QualityBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.QualityBox.TabIndex = 4;
            this.QualityBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.QualityBox.TextMarginBottom = 0;
            this.QualityBox.TextMarginLeft = 3;
            this.QualityBox.TextMarginTop = 0;
            this.QualityBox.TextPlaceholder = "Enter text";
            this.QualityBox.UseSystemPasswordChar = false;
            this.QualityBox.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Sans Serif Collection", 8.25F);
            this.bunifuLabel3.Location = new System.Drawing.Point(303, 114);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(59, 27);
            this.bunifuLabel3.TabIndex = 0;
            this.bunifuLabel3.Text = "Quality:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TypeBox
            // 
            this.TypeBox.AcceptsReturn = false;
            this.TypeBox.AcceptsTab = false;
            this.TypeBox.AnimationSpeed = 200;
            this.TypeBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TypeBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TypeBox.BackColor = System.Drawing.Color.Transparent;
            this.TypeBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TypeBox.BackgroundImage")));
            this.TypeBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TypeBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TypeBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TypeBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.TypeBox.BorderRadius = 15;
            this.TypeBox.BorderThickness = 1;
            this.TypeBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TypeBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TypeBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.TypeBox.DefaultText = "";
            this.TypeBox.FillColor = System.Drawing.Color.White;
            this.TypeBox.HideSelection = true;
            this.TypeBox.IconLeft = null;
            this.TypeBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TypeBox.IconPadding = 10;
            this.TypeBox.IconRight = null;
            this.TypeBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TypeBox.Lines = new string[0];
            this.TypeBox.Location = new System.Drawing.Point(418, 54);
            this.TypeBox.MaxLength = 32767;
            this.TypeBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.TypeBox.Modified = false;
            this.TypeBox.Multiline = false;
            this.TypeBox.Name = "TypeBox";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TypeBox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TypeBox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TypeBox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TypeBox.OnIdleState = stateProperties8;
            this.TypeBox.Padding = new System.Windows.Forms.Padding(3);
            this.TypeBox.PasswordChar = '\0';
            this.TypeBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TypeBox.PlaceholderText = "Enter text";
            this.TypeBox.ReadOnly = false;
            this.TypeBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TypeBox.SelectedText = "";
            this.TypeBox.SelectionLength = 0;
            this.TypeBox.SelectionStart = 0;
            this.TypeBox.ShortcutsEnabled = true;
            this.TypeBox.Size = new System.Drawing.Size(152, 37);
            this.TypeBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TypeBox.TabIndex = 2;
            this.TypeBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TypeBox.TextMarginBottom = 0;
            this.TypeBox.TextMarginLeft = 3;
            this.TypeBox.TextMarginTop = 0;
            this.TypeBox.TextPlaceholder = "Enter text";
            this.TypeBox.UseSystemPasswordChar = false;
            this.TypeBox.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Sans Serif Collection", 8.25F);
            this.bunifuLabel2.Location = new System.Drawing.Point(303, 61);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(109, 27);
            this.bunifuLabel2.TabIndex = 0;
            this.bunifuLabel2.Text = "Product Type:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // PriceBox
            // 
            this.PriceBox.AcceptsReturn = false;
            this.PriceBox.AcceptsTab = false;
            this.PriceBox.AnimationSpeed = 200;
            this.PriceBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.PriceBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.PriceBox.BackColor = System.Drawing.Color.Transparent;
            this.PriceBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PriceBox.BackgroundImage")));
            this.PriceBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.PriceBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PriceBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PriceBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.PriceBox.BorderRadius = 15;
            this.PriceBox.BorderThickness = 1;
            this.PriceBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.PriceBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.PriceBox.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PriceBox.DefaultText = "";
            this.PriceBox.FillColor = System.Drawing.Color.White;
            this.PriceBox.HideSelection = true;
            this.PriceBox.IconLeft = null;
            this.PriceBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.PriceBox.IconPadding = 10;
            this.PriceBox.IconRight = null;
            this.PriceBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.PriceBox.Lines = new string[0];
            this.PriceBox.Location = new System.Drawing.Point(141, 155);
            this.PriceBox.MaxLength = 32767;
            this.PriceBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.PriceBox.Modified = false;
            this.PriceBox.Multiline = false;
            this.PriceBox.Name = "PriceBox";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PriceBox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.PriceBox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PriceBox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PriceBox.OnIdleState = stateProperties12;
            this.PriceBox.Padding = new System.Windows.Forms.Padding(3);
            this.PriceBox.PasswordChar = '\0';
            this.PriceBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.PriceBox.PlaceholderText = "Enter text";
            this.PriceBox.ReadOnly = false;
            this.PriceBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.PriceBox.SelectedText = "";
            this.PriceBox.SelectionLength = 0;
            this.PriceBox.SelectionStart = 0;
            this.PriceBox.ShortcutsEnabled = true;
            this.PriceBox.Size = new System.Drawing.Size(152, 39);
            this.PriceBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.PriceBox.TabIndex = 5;
            this.PriceBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.PriceBox.TextMarginBottom = 0;
            this.PriceBox.TextMarginLeft = 3;
            this.PriceBox.TextMarginTop = 0;
            this.PriceBox.TextPlaceholder = "Enter text";
            this.PriceBox.UseSystemPasswordChar = false;
            this.PriceBox.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Sans Serif Collection", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel5.Location = new System.Drawing.Point(20, 162);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(58, 32);
            this.bunifuLabel5.TabIndex = 0;
            this.bunifuLabel5.Text = "Price:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // QuantityBox
            // 
            this.QuantityBox.AcceptsReturn = false;
            this.QuantityBox.AcceptsTab = false;
            this.QuantityBox.AnimationSpeed = 200;
            this.QuantityBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.QuantityBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.QuantityBox.BackColor = System.Drawing.Color.Transparent;
            this.QuantityBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("QuantityBox.BackgroundImage")));
            this.QuantityBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.QuantityBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.QuantityBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.QuantityBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.QuantityBox.BorderRadius = 15;
            this.QuantityBox.BorderThickness = 1;
            this.QuantityBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.QuantityBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.QuantityBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.QuantityBox.DefaultText = "";
            this.QuantityBox.FillColor = System.Drawing.Color.White;
            this.QuantityBox.HideSelection = true;
            this.QuantityBox.IconLeft = null;
            this.QuantityBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.QuantityBox.IconPadding = 10;
            this.QuantityBox.IconRight = null;
            this.QuantityBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.QuantityBox.Lines = new string[0];
            this.QuantityBox.Location = new System.Drawing.Point(141, 107);
            this.QuantityBox.MaxLength = 32767;
            this.QuantityBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.QuantityBox.Modified = false;
            this.QuantityBox.Multiline = false;
            this.QuantityBox.Name = "QuantityBox";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.QuantityBox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.QuantityBox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.QuantityBox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.QuantityBox.OnIdleState = stateProperties16;
            this.QuantityBox.Padding = new System.Windows.Forms.Padding(3);
            this.QuantityBox.PasswordChar = '\0';
            this.QuantityBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.QuantityBox.PlaceholderText = "Enter text";
            this.QuantityBox.ReadOnly = false;
            this.QuantityBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.QuantityBox.SelectedText = "";
            this.QuantityBox.SelectionLength = 0;
            this.QuantityBox.SelectionStart = 0;
            this.QuantityBox.ShortcutsEnabled = true;
            this.QuantityBox.Size = new System.Drawing.Size(152, 37);
            this.QuantityBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.QuantityBox.TabIndex = 3;
            this.QuantityBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.QuantityBox.TextMarginBottom = 0;
            this.QuantityBox.TextMarginLeft = 3;
            this.QuantityBox.TextMarginTop = 0;
            this.QuantityBox.TextPlaceholder = "Enter text";
            this.QuantityBox.UseSystemPasswordChar = false;
            this.QuantityBox.WordWrap = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Sans Serif Collection", 8.25F);
            this.bunifuLabel4.Location = new System.Drawing.Point(20, 114);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(70, 27);
            this.bunifuLabel4.TabIndex = 0;
            this.bunifuLabel4.Text = "Quantity:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // NameBox
            // 
            this.NameBox.AcceptsReturn = false;
            this.NameBox.AcceptsTab = false;
            this.NameBox.AnimationSpeed = 200;
            this.NameBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.NameBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.NameBox.BackColor = System.Drawing.Color.Transparent;
            this.NameBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("NameBox.BackgroundImage")));
            this.NameBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.NameBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NameBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NameBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.NameBox.BorderRadius = 15;
            this.NameBox.BorderThickness = 1;
            this.NameBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.NameBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.NameBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.NameBox.DefaultText = "";
            this.NameBox.FillColor = System.Drawing.Color.White;
            this.NameBox.HideSelection = true;
            this.NameBox.IconLeft = null;
            this.NameBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.NameBox.IconPadding = 10;
            this.NameBox.IconRight = null;
            this.NameBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.NameBox.Lines = new string[0];
            this.NameBox.Location = new System.Drawing.Point(141, 54);
            this.NameBox.MaxLength = 32767;
            this.NameBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.NameBox.Modified = false;
            this.NameBox.Multiline = false;
            this.NameBox.Name = "NameBox";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NameBox.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.NameBox.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NameBox.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NameBox.OnIdleState = stateProperties20;
            this.NameBox.Padding = new System.Windows.Forms.Padding(3);
            this.NameBox.PasswordChar = '\0';
            this.NameBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.NameBox.PlaceholderText = "Enter text";
            this.NameBox.ReadOnly = false;
            this.NameBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.NameBox.SelectedText = "";
            this.NameBox.SelectionLength = 0;
            this.NameBox.SelectionStart = 0;
            this.NameBox.ShortcutsEnabled = true;
            this.NameBox.Size = new System.Drawing.Size(152, 37);
            this.NameBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.NameBox.TabIndex = 1;
            this.NameBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.NameBox.TextMarginBottom = 0;
            this.NameBox.TextMarginLeft = 3;
            this.NameBox.TextMarginTop = 0;
            this.NameBox.TextPlaceholder = "Enter text";
            this.NameBox.UseSystemPasswordChar = false;
            this.NameBox.WordWrap = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Bebas", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.Location = new System.Drawing.Point(20, 16);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(108, 29);
            this.bunifuLabel6.TabIndex = 0;
            this.bunifuLabel6.Text = "Add Product";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Sans Serif Collection", 8.25F);
            this.bunifuLabel1.Location = new System.Drawing.Point(20, 61);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(115, 27);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "Product Name:";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 20;
            this.bunifuElipse1.TargetControl = this;
            // 
            // Product
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(245)))), ((int)(((byte)(224)))));
            this.ClientSize = new System.Drawing.Size(810, 605);
            this.Controls.Add(this.bunifuShadowPanel1);
            this.Controls.Add(this.bunifuShadowPanel6);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Product";
            this.Text = "Product";
            this.Load += new System.EventHandler(this.Product_Load);
            this.bunifuShadowPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ProductsGridView)).EndInit();
            this.bunifuShadowPanel6.ResumeLayout(false);
            this.bunifuShadowPanel6.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuDataGridView ProductsGridView;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel4;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel6;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AddButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton RemoveButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton UpdateButton;
        private Bunifu.UI.WinForms.BunifuTextBox QualityBox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox TypeBox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox PriceBox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox QuantityBox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox NameBox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
    }
}